# flake8: noqa: E501
"""init

Revision ID: 3dc91ae6a2ad
Revises:
Create Date: 2025-12-24 11:06:56.385530

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3dc91ae6a2ad"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("customer_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invoice_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invoice_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("contact_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "messaging_app_line", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "primary_contact", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "customer_type",
            sa.Enum(
                "REAL_ESTATE",
                "EDUCATION",
                "ELEMENTARY_ATTACHED_KINDERGARTEN",
                "COMPANY",
                "INSURANCE",
                "OTHER",
                name="customertype",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("name", sa.String(length=4), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "user_type", sa.Enum("ADMIN", "NORMAL", name="usertype"), nullable=False
        ),
        sa.Column("contact_phone", sa.String(), nullable=False),
        sa.Column(
            "messaging_app_line", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_phone"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("customer")
    # ### end Alembic commands ###
