"""init

Revision ID: 665952fc9d6c
Revises:
Create Date: 2025-12-03 11:18:35.574642

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "665952fc9d6c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("customer_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # noqa: E501
        sa.Column("invoice_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # noqa: E501
        sa.Column("invoice_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # noqa: E501
        sa.Column("contact_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # noqa: E501
        sa.Column(
            "messaging_app_line",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,  # noqa: E501
        ),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # noqa: E501
        sa.Column(
            "primary_contact",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,  # noqa: E501
        ),
        sa.Column(
            "customer_type",
            sa.Enum(
                "REAL_ESTATE",
                "EDUCATION",
                "ELEMENTARY_ATTACHED_KINDERGARTEN",
                "COMPANY",
                "INSURANCE",
                "OTHER",
                name="customertype",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("customer")
    # ### end Alembic commands ###
