# flake8: noqa: E501
"""init

Revision ID: ea68ff45c522
Revises:
Create Date: 2025-12-26 10:15:24.915003

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ea68ff45c522"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("customer_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invoice_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invoice_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("contact_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "messaging_app_line", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "primary_contact", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "customer_type",
            sa.Enum(
                "REAL_ESTATE",
                "EDUCATION",
                "ELEMENTARY_ATTACHED_KINDERGARTEN",
                "COMPANY",
                "INSURANCE",
                "OTHER",
                name="customertype",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("name", sa.String(length=4), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "user_type", sa.Enum("ADMIN", "NORMAL", name="usertype"), nullable=False
        ),
        sa.Column("contact_phone", sa.String(), nullable=False),
        sa.Column(
            "messaging_app_line", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_phone"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "contract",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("product_name", sa.String(length=30), nullable=False),
        sa.Column("start_date", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("end_date", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("monthly_rent", sa.INTEGER(), nullable=False),
        sa.Column(
            "billing_interval",
            postgresql.ENUM(
                "THREE_MONTHS",
                "SIX_MONTHS",
                "TWELVE_MONTHS",
                "TWENTY_FOUR_MONTHS",
                name="billinginterval",
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=300), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE",
                "EXPIRED",
                "TERMINATED",
                "PENDING",
                "SUSPENDED",
                name="contractstatus",
            ),
            nullable=False,
        ),
        sa.Column("contract_number", sa.String(), nullable=True),
        sa.Column("signed_date", postgresql.TIMESTAMP(), nullable=True),
        sa.Column(
            "payment_method",
            postgresql.ENUM(
                "BANK_TRANSFER", "CASH", "CHECK", "OTHER", name="paymentmethod"
            ),
            nullable=True,
        ),
        sa.Column("next_billing_date", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("terminated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("termination_reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contract")
    op.drop_table("user")
    op.drop_table("customer")
    # ### end Alembic commands ###
